apiVersion: v1
kind: Service
metadata:
  name: prometheus-assingnment-service
spec:
  selector:
    app: prometheus-assingnment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30070
  type: NodePort